name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          $assemblyInfoPath = "SystemMonitoring/Properties/AssemblyInfo.cs"
          if (-Not (Test-Path $assemblyInfoPath)) {
            Write-Error "AssemblyInfo.cs not found at $assemblyInfoPath"
            exit 1
          }
          $content = Get-Content -Path $assemblyInfoPath
          $versionLine = $content | Where-Object { $_ -match '^\s*\[assembly:\s*AssemblyVersion\("([^"]+)"\)\]' }
          if (-Not $versionLine) {
            Write-Error "AssemblyVersion not found in $assemblyInfoPath"
            exit 1
          }
          $version = ($versionLine -replace '^\s*\[assembly:\s*AssemblyVersion\("([^"]+)"\)\].*', '$1')
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Clean the project
        run: msbuild "SystemMonitoring/system-monitoring.csproj" /t:Clean /p:Configuration=Release

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build the project
        run: msbuild "SystemMonitoring/system-monitoring.csproj" /p:Configuration=Release /p:OutputPath=${{ github.workspace }}/publish

      - name: List files in publish directory
        run: ls -R ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: System-Monitoring-v${{ steps.get_version.outputs.version }}
          path: ./publish
